### ISSUE TITLE
CI/CD-compliant migrations for Lockbox

### ISSUE THREAD

**Issue by xanadiu** [ankane/lockbox#118]
I am currently integrating Lockbox into an existing Rails project for the first time. The gem seems to be well thought and designed, thanks for your effort and your contribution.

As I am migrating currently non-encrypted data, I am wondering if there is a way to encapsulate the required steps into one transaction (ideally based on a Rails migration).

Why am I asking? This becomes relevant as I am using GitLab CI/CD for deploying code without direct interaction. Usually the deployment pipeline pushes the code and executes any pending migrations. After this, the application is expected to work again. But as far as I can see, Lockbox requires manual intervention. IMHO this is in contrast to the statement _"Lockbox makes it easy to encrypt an existing column without downtime"_ in the README.

I think I found a way to "trick" Lockbox with a (also revertible) migration that satisfies my needs, but that rather looks like a dirty and error-prone workaround (at least it worked for me):

```
class AddCiphertextAndBlindIndex < ActiveRecord::Migration[6.0]
  def up
    add_column :users, :email_ciphertext, :text
    add_column :users, :email_bidx, :string

    User.reset_column_information

    User.all.each do |obj|
      User.where(id: obj.id).update_all(
        email_ciphertext: User.generate_email_ciphertext(obj.email)
      )
    end

    BlindIndex.backfill(User, columns: [:email_bidx])

    remove_column :users, :email

    add_index :users, :email_bidx, unique: true
  end

  def down
    add_column :users, :email, :string, default: '', null: false

    User.reset_column_information

    User.all.each do |obj|
      User.where(id: obj.id).update_all(
        email: User.decrypt_email_ciphertext(obj.email_ciphertext)
      )
    end

    remove_column :users, :email_ciphertext, :text
    remove_column :users, :email_bidx, :string

    add_index :users, :email, unique: true
  end
end
```

Explanation: I had to update the `User` objects in this complicated way to keep Lockbox from complaining about directly accessing the attributes.

If it is possible to better support such migration situations by Lockbox directly, that would be awesome.

Michael

**Comment by ankane** [comment]
Hey @xanadiu, the above approach should work if you're okay with downtime. Lockbox doesn't require any manual intervention (you can put the `Model.migrate` step in a migration instead of running it in the Rails console), but it does need multiple deploys for zero downtime. The main steps in migrating are:

1. Add a new column
2. Tell the application code to start writing to the new column (in addition to the old column)
3. Migrate the data
4. Tell the application code to start reading from the new column
5. Drop the old column

There's not a simple way to do steps 2 and 4 with a single deploy/migration.

See #78 for previous discussion.
