### ISSUE TITLE
Slow Specs

### ISSUE THREAD

**Issue by sirwolfgang** [ankane/lockbox#144]
Is there a way to disable or swap out the encryption algorithm for something lightweight during specs? 

After migrating from plain text to encrypted, it takes 5x as long to run our test suit.

**Comment by sirwolfgang** [comment]
We are using blind indexing. 

It went from ~2.5 mins to ~10 mins for our unit test suite on CI. 

It's not a show stopper by any means, but for something like bcrypt I am used to being able to lower the cost. Hoping there's a way to do that? I don't want to fully monkey-patch to disable encrypt and decrypt to plain text, because it would then be easier to let it slip when it wasn't workering.

**Comment by ankane** [comment]
My guess is it's due to blind indexing (which is designed to be slow) rather than encryption, but would be good to profile a test or two to see if that's the case. There's not a way to set really low costs for blind indexing right now (for security), but it may make sense to add some sort of test mode. In the meantime, you can fork the `blind_index` gem and [remove the cost checks](https://github.com/ankane/blind_index/blob/44166f7a4ac0abbccb568d15d83e2dc053f5f57b/lib/blind_index.rb#L59-L66) to set low costs.

**Comment by ankane** [comment]
Cleaning up stale issues
