### ISSUE TITLE
Add XChaCha20 algorithm to README

### ISSUE THREAD

**Issue by pbstriker38** [ankane/lockbox#20]
When XSalsa20 support was added, XChaCha20 was removed from the README. Was this on purpose?

**Comment by ankane** [comment]
Hey @pbstriker38, it was on purpose as I wanted to keep it as simple as possible for users. I chose XSalsa20 since many platforms (Ubuntu 16.04, Heroku-16, Travis, Circle) make it easy to install `libsodium18` but `libsodium23` is required for XChaCha20.

XChaCha20 is still fully supported and will likely replace XSalsa20 in the future. Hopefully it'll become [a standard](https://datatracker.ietf.org/doc/draft-arciszewski-xchacha/) in the next few years.
