### ISSUE TITLE
Lockbox with Devise confirmable module weirdness

### ISSUE THREAD

**Issue by bmclean** [ankane/lockbox#24]
When using Devise with the confirmable module when a user edits their email address the new email value is stored in the `unconfirmed_email` attribute and the original email stays in the `email` attribute. Once the change has been confirmed the `unconfirmed_email` is copied over to `email`. This happens in a before_update callback within the confirmable module in the `postpone_email_change_until_confirmation_and_regenerate_confirmation_token` method which looks something like this:
```
self.unconfirmed_email = self.email
self.email = self.email_in_database
self.confirmation_token = nil
generate_confirmation_token
```
When also using Lockbox with Blind Index in this scenario by the time the above code executes the `email_ciphertext` and `email_bidx` already have changed values. This results in the user being able to sign in with the new email address before it has been confirmed.

I added the following to my User model which seems to retain the original Devise functionality:
```
  def postpone_email_change_until_confirmation_and_regenerate_confirmation_token
    super
    restore_email_bidx! if email_bidx_changed?
    restore_email_ciphertext! if email_ciphertext_changed?
  end
```
Would this be something that could be handled by the Lockbox / Blind Index gems?

**Comment by ankane** [comment]
Hey @bmclean, thanks for the detailed report. The issue is the Blind Index gem doesn't detect changes in ActiveRecord callbacks. Here's the flow of events:

1. Devise updates email
2. Blind index updated in `before_validation` hook
3. Devise reverts email change in `before_update` hook
4. Blind index never reverted

The ciphertext also changes, but the plaintext is still the same when you decrypt it.

The ideal solution is for blind indexes to be updated immediately whenever the encrypted field is updated. However, I think this will be difficult since there's not an ActiveRecord API for it.

Lockbox could have logic to specifically handle blind indexes. However, the most obvious way to do this would cause the blind index to always be recalculated twice (once immediately and then again in the `before_validation` callback since Blind Index needs to support more than just Lockbox), and the blind index calculation is purposefully slow.

For now, I've updated [the article](https://ankane.org/securing-user-emails-lockbox#reconfirmable) with your fix, but will continue to think on a better solution.

**Comment by bmclean** [comment]
Sounds good @ankane. This makes sense. Thanks!

**Comment by ankane** [comment]
Hey @bmclean, Blind Index 2.0 was just released which now updates blind indexes immediately instead of in a `before_validation` callback. Overriding `postpone_email_change_until_confirmation_and_regenerate_confirmation_token` should no longer be needed. No more weirdness!

**Comment by bmclean** [comment]
I removed the override and tested with Blind Index 2.0. It works great. Thanks @ankane!

**Comment by vitobotta** [comment]
I was getting crazy with this after someone noticed this behaviour.... I eventually thought it might be related to the encryption and found this. Glad I just needed to upgrade :)

**Comment by vitobotta** [comment]
@ankane I am having a related issue tho. I have configured Devise to send a notification to the user when the email is being changed, but when the email is rendered `@resource.unconfirmed_email` is blank so the new email address is not shown in the email. Any possible fix? Thanks

**Comment by vitobotta** [comment]
I solved by delaying that notification a couple of seconds.
