### ISSUE TITLE
Lockbox and Devise two_factor_authenticatable

### ISSUE THREAD

**Issue by tbcooney** [ankane/lockbox#27]
I came across Lockbox the other day while looking at some guides around [securing sensitive data in a Rails app](https://ankane.org/sensitive-data-rails), and found it to be a good candidate to migrate my existing two-factor setup, using [devise-two-factor](https://github.com/tinfoil/devise-two-factor). The `devise-two-factor` generator adds a few columns to the specified model:

- encrypted_otp_secret
- encrypted_otp_secret_iv
- encrypted_otp_secret_salt
- consumed_timestep
- otp_required_for_login

Furthermore, `devise-two-factor` encrypts its secrets before storing them in the database - I have an encryption key stored as an environment variable. The encryption key is set in the specified model that uses Devise:

```
 devise :two_factor_authenticatable,
         :otp_secret_encryption_key => ENV['ENCRYPTION_KEY']
```

I know Lockbox makes it easy to migrate from another library, and I'll admit that I haven't given this a go yet, but I was curious if you had any suggestions on how to support this.

**Comment by ankane** [comment]
Hey @tbcooney, looking at the gem, I think it's easiest to just use it as is. There shouldn't be much downside to having `attr_encrypted` manage that specific field, even if you use Lockbox for other fields.

If you wanted to adapt the gem to Lockbox, you could:

1. Replace `encrypted_otp_secret`, `encrypted_otp_secret_iv` and `encrypted_otp_secret_salt` with `otp_secret_ciphertext` in the migration
2. Change [https://github.com/tinfoil/devise-two-factor/blob/07acb0ae50689f9c7fe57acceff8d2ff949d25fb/lib/devise_two_factor/models/two_factor_authenticatable.rb#L11-L19](https://github.com/tinfoil/devise-two-factor/blob/master/lib/devise_two_factor/models/two_factor_authenticatable.rb) to use `encrypts :opt_secret, key: self.otp_secret_encryption_key` instead of `attr_encrypted :otp_secret, ...`
3. Change `required_fields` in the same file

`otp_secret_encryption_key` would be optional since Lockbox can use the master key to generate a key for that field if desired.

Does that make sense?

**Comment by tbcooney** [comment]
Understood 👌 I might run the two in parallel and save the additional work - if I can't bear to look at it I'll update back here with some results.

**Comment by ankane** [comment]
Sounds good!
