### ISSUE TITLE
Ciphertext field type should be 'text', why?

### ISSUE THREAD

**Issue by glebglazov** [ankane/lockbox#59]
Hi Andrew, thanks for a gem!

I was wondering, why the type of a ciphertext column should be a "text"? What's the reasoning behind that? Is that because of a default size of a blob columns (65535 bytes) or some rails-specific shenanigans that are not possible with VARCHAR?

Cause in my opinion it could be a good option to use VARCHAR in some cases (when you don't want separate reads of data performed by DB: one from a page when all the data of a row is situated and the other one from "blob" storage of your DB)

**Comment by ankane** [comment]
Hey @glebglazov, you should be able to use `VARCHAR` without any issues (just keep in mind the ciphertext will be longer than the plaintext). The readme recommends `text` since it has a higher character limit and there's no difference between the two in Postgres (besides a constraint if the `VARCHAR` has a character limit).

Alternatively, you can use a binary type: https://github.com/ankane/lockbox#binary-columns

**Comment by glebglazov** [comment]
Thanks for the answer!
